# Generated by Django 5.2 on 2025-04-25 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('PRINCIPIANTE', 'Principiante'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado')], max_length=20)),
                ('pregunta', models.TextField()),
                ('opcion_a', models.CharField(max_length=200)),
                ('opcion_b', models.CharField(max_length=200)),
                ('opcion_c', models.CharField(max_length=200)),
                ('opcion_d', models.CharField(max_length=200)),
                ('respuesta_correcta', models.CharField(max_length=1)),
                ('explicacion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='evaluacion_completada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_evaluacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nivel_programacion',
            field=models.CharField(blank=True, choices=[('NO_EXPERIENCIA', 'No, es mi primera vez'), ('PRINCIPIANTE', 'Sí, pero muy poco'), ('INTERMEDIO', 'Sí, nivel intermedio'), ('AVANZADO', 'Sí, nivel avanzado')], max_length=20, null=True, verbose_name='Nivel de Programación'),
        ),
        migrations.AddField(
            model_name='user',
            name='puntaje_evaluacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ResultadoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_seleccionado', models.CharField(choices=[('NO_EXPERIENCIA', 'No, es mi primera vez'), ('PRINCIPIANTE', 'Sí, pero muy poco'), ('INTERMEDIO', 'Sí, nivel intermedio'), ('AVANZADO', 'Sí, nivel avanzado')], max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('preguntas_correctas', models.IntegerField(default=0)),
                ('preguntas_totales', models.IntegerField(default=0)),
                ('nivel_asignado', models.CharField(blank=True, choices=[('NO_EXPERIENCIA', 'No, es mi primera vez'), ('PRINCIPIANTE', 'Sí, pero muy poco'), ('INTERMEDIO', 'Sí, nivel intermedio'), ('AVANZADO', 'Sí, nivel avanzado')], max_length=20, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_evaluacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_seleccionada', models.CharField(max_length=1)),
                ('es_correcta', models.BooleanField()),
                ('tiempo_respuesta', models.DurationField(blank=True, null=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.preguntaevaluacion')),
                ('resultado_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='users.resultadoevaluacion')),
            ],
        ),
    ]
