# Generated by Django 5.2 on 2025-04-25 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_preguntaevaluacion_user_evaluacion_completada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadoevaluacion',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='user',
            name='evaluacion_completada',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fecha_evaluacion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nivel_programacion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='puntaje_evaluacion',
        ),
        migrations.AddField(
            model_name='user',
            name='programming_level',
            field=models.CharField(blank=True, choices=[('NO_EXPERIENCIA', 'Sin Experiencia'), ('PRINCIPIANTE', 'Principiante'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='preguntaevaluacion',
            name='nivel',
            field=models.CharField(choices=[('NO_EXPERIENCIA', 'Sin Experiencia'), ('PRINCIPIANTE', 'Principiante'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='EvaluacionDiagnostica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('EN_PROGRESO', 'En Progreso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='EN_PROGRESO', max_length=20)),
                ('nivel_seleccionado', models.CharField(choices=[('NO_EXPERIENCIA', 'Sin Experiencia'), ('PRINCIPIANTE', 'Principiante'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado')], max_length=20)),
                ('nivel_asignado', models.CharField(blank=True, choices=[('NO_EXPERIENCIA', 'Sin Experiencia'), ('PRINCIPIANTE', 'Principiante'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado')], max_length=20, null=True)),
                ('preguntas', models.ManyToManyField(to='users.preguntaevaluacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_seleccionada', models.CharField(max_length=1)),
                ('tiempo_respuesta', models.FloatField()),
                ('es_correcta', models.BooleanField(default=False)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='users.evaluaciondiagnostica')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.preguntaevaluacion')),
            ],
            options={
                'ordering': ['fecha_respuesta'],
            },
        ),
        migrations.DeleteModel(
            name='RespuestaUsuario',
        ),
        migrations.DeleteModel(
            name='ResultadoEvaluacion',
        ),
    ]
