# Generated by Django 5.1.2 on 2025-05-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='nivel',
            field=models.CharField(choices=[('NO_EXPERIENCIA', 'No experiencia'), ('PRINCIPIANTE', 'Principiante'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado')], max_length=20),
        ),
    ]
